# Data Preperation
## importing necessary modules

In [1]:
import numpy as np 
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
import re

In [3]:
import os 
from pathlib import Path

"""project_root = Path.cwd().parent.parent
data_path = project_root / 'data'/ 'processed' / 'final_dataset.csv'

file_path = r"e:/dm4ml project/data/processed/final_dataset.csv"

chunk_size = 100_000
sample_frac = 0.05

sampled_chunk = []

for chunk in pd.read_csv(file_path, chunksize=chunk_size):
    sampled = chunk.sample(frac=sample_frac, random_state = 42)
    sampled_chunk.append(sampled)

df1 = pd.concat(sampled_chunk, ignore_index=True)"""
df1 = pd.read_csv(r"e:/dm4ml project/data/processed/final_dataset.csv")

In [4]:
df1

,user_id,product_id,interaction_type,rating_x,timestamp,id,title,description,category,price,discountPercentage,rating_y,stock,tags,brand,sku,weight,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,2949,19,purchase,5,2026-04-01 21:17:02.978853,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,['meat'],NaN,GRO-BRD-CHI-019,1,"{'width': 11.03, 'height': 22.11, 'depth': 16.01}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
1,6162,24,view,3,2026-04-04 21:17:02.978866,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,['seafood'],NaN,GRO-BRD-FIS-024,6,"{'width': 14.95, 'height': 26.31, 'depth': 11.27}",1 month warranty,Ships in 3-5 business days,In Stock,"[{'rating': 2, 'comment': 'Would not buy again...",60 days return policy,50,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
2,6396,26,view,5,2026-03-23 21:17:02.978869,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,['vegetables'],NaN,GRO-BRD-GRE-026,7,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
3,9025,30,view,3,2026-04-11 21:17:02.978871,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,['fruits'],NaN,GRO-BRD-KIW-030,5,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
4,1372,16,view,5,2026-03-21 21:17:02.978873,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,['fruits'],NaN,GRO-BRD-APP-016,9,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524995,8085,15,purchase,1,2026-04-13 21:17:03.002889,15,Wooden Bathroom Sink With Mirror,The Wooden Bathroom Sink with Mirror is a uniq...,furniture,799.99,8.80,3.59,7,"['furniture', 'bathroom']",Bath Trends,FUR-BAT-WOO-015,10,"{'width': 7.98, 'height': 8.88, 'depth': 28.46}",3 year warranty,Ships in 3-5 business days,Low Stock,"[{'rating': 4, 'comment': 'Fast shipping!', 'd...",60 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/fur...,https://cdn.dummyjson.com/product-images/furni...
524996,4473,20,click,4,2026-03-24 21:17:03.002891,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,['cooking essentials'],NaN,GRO-BRD-COO-020,5,"{'width': 19.95, 'height': 27.54, 'depth': 24.86}",Lifetime warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Very happy with my ...",30 days return policy,46,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
524997,4520,16,purchase,5,2026-04-05 21:17:03.002893,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,['fruits'],NaN,GRO-BRD-APP-016,9,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
524998,7886,30,view,3,2026-03-19 21:17:03.002895,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,['fruits'],NaN,GRO-BRD-KIW-030,5,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
524999,8666,5,view,5,2026-04-06 21:17:03.002897,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"['beauty', 'nail polish']",Nail Couture,BEA-NAI-NAI-005,8,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/bea...,https://cdn.dummyjson.com/product-images/beaut...

In [5]:
df1.head(10)

,user_id,product_id,interaction_type,rating_x,timestamp,id,title,description,category,price,discountPercentage,rating_y,stock,tags,brand,sku,weight,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,2949,19,purchase,5,2026-04-01 21:17:02.978853,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,['meat'],NaN,GRO-BRD-CHI-019,1,"{'width': 11.03, 'height': 22.11, 'depth': 16.01}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
1,6162,24,view,3,2026-04-04 21:17:02.978866,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,['seafood'],NaN,GRO-BRD-FIS-024,6,"{'width': 14.95, 'height': 26.31, 'depth': 11.27}",1 month warranty,Ships in 3-5 business days,In Stock,"[{'rating': 2, 'comment': 'Would not buy again...",60 days return policy,50,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
2,6396,26,view,5,2026-03-23 21:17:02.978869,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,['vegetables'],NaN,GRO-BRD-GRE-026,7,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
3,9025,30,view,3,2026-04-11 21:17:02.978871,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,['fruits'],NaN,GRO-BRD-KIW-030,5,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
4,1372,16,view,5,2026-03-21 21:17:02.978873,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,['fruits'],NaN,GRO-BRD-APP-016,9,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
5,5944,22,click,1,2026-03-24 21:17:02.978875,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"['pet supplies', 'dog food']",NaN,GRO-BRD-FOO-022,10,"{'width': 16.93, 'height': 27.15, 'depth': 9.29}",No warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
6,5581,15,click,2,2026-04-05 21:17:02.978877,15,Wooden Bathroom Sink With Mirror,The Wooden Bathroom Sink with Mirror is a uniq...,furniture,799.99,8.80,3.59,7,"['furniture', 'bathroom']",Bath Trends,FUR-BAT-WOO-015,10,"{'width': 7.98, 'height': 8.88, 'depth': 28.46}",3 year warranty,Ships in 3-5 business days,Low Stock,"[{'rating': 4, 'comment': 'Fast shipping!', 'd...",60 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/fur...,https://cdn.dummyjson.com/product-images/furni...
7,6675,22,click,4,2026-04-03 21:17:02.978878,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"['pet supplies', 'dog food']",NaN,GRO-BRD-FOO-022,10,"{'width': 16.93, 'height': 27.15, 'depth': 9.29}",No warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
8,9332,23,purchase,3,2026-03-16 21:17:02.978880,23,Eggs,"Fresh eggs, a versatile ingredient for baking,...",groceries,2.99,11.05,2.53,9,['dairy'],NaN,GRO-BRD-EGG-023,2,"{'width': 11.42, 'height': 7.44, 'depth': 16.95}",1 week warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Disappointing produ...",No return policy,32,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
9,4279,20,click,1,2026-03-16 21:17:02.978882,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,['cooking essentials'],NaN,GRO-BRD-COO-020,5,"{'width': 19.95, 'height': 27.54, 'depth': 24.86}",Lifetime warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Very happy with my ...",30 days return policy,46,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525000 entries, 0 to 524999
Data columns (total 27 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   user_id               525000 non-null  int64
 1   product_id            525000 non-null  int64
 2   interaction_type      525000 non-null  object
 3   rating_x              525000 non-null  int64
 4   timestamp             525000 non-null  object
 5   id                    525000 non-null  int64
 6   title                 525000 non-null  object
 7   description           525000 non-null  object
 8   category              525000 non-null  object
 9   price                 525000 non-null  float64
 10  discountPercentage    525000 non-null  float64
 11  rating_y              525000 non-null  float64
 12  stock                 525000 non-null  int64
 13  tags                  525000 non-null  object
 14  brand                 263445 non-null  object
 15  sku                   525000 non-null  object
 16  weight                525000 non-null  int64
 17  dimensions            525000 non-null  object
 18  warrantyInformation   525000 non-null  object
 19  shippingInformation   525000 non-null  object
 20  availabilityStatus    525000 non-null  object
 21  reviews               525000 non-null  object
 22  returnPolicy          525000 non-null  object
 23  minimumOrderQuantity  525000 non-null  int64
 24  meta                  525000 non-null  object
 25  images                525000 non-null  object
 26  thumbnail             525000 non-null  object
dtypes: float64(3), int64(7), object(17)
memory usage: 108.1+ MB

In [7]:
df1.replace('?', np.nan, inplace=True)
df1.head()

,user_id,product_id,interaction_type,rating_x,timestamp,id,title,description,category,price,discountPercentage,rating_y,stock,tags,brand,sku,weight,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,2949,19,purchase,5,2026-04-01 21:17:02.978853,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,['meat'],NaN,GRO-BRD-CHI-019,1,"{'width': 11.03, 'height': 22.11, 'depth': 16.01}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
1,6162,24,view,3,2026-04-04 21:17:02.978866,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,['seafood'],NaN,GRO-BRD-FIS-024,6,"{'width': 14.95, 'height': 26.31, 'depth': 11.27}",1 month warranty,Ships in 3-5 business days,In Stock,"[{'rating': 2, 'comment': 'Would not buy again...",60 days return policy,50,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
2,6396,26,view,5,2026-03-23 21:17:02.978869,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,['vegetables'],NaN,GRO-BRD-GRE-026,7,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
3,9025,30,view,3,2026-04-11 21:17:02.978871,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,['fruits'],NaN,GRO-BRD-KIW-030,5,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...
4,1372,16,view,5,2026-03-21 21:17:02.978873,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,['fruits'],NaN,GRO-BRD-APP-016,9,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...

In [8]:
missing_data = df1.isnull()
missing_data.head(10)

,user_id,product_id,interaction_type,rating_x,timestamp,id,title,description,category,price,discountPercentage,rating_y,stock,tags,brand,sku,weight,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

user_id
user_id
False    525000
Name: count, dtype: int64

product_id
product_id
False    525000
Name: count, dtype: int64

interaction_type
interaction_type
False    525000
Name: count, dtype: int64

rating_x
rating_x
False    525000
Name: count, dtype: int64

timestamp
timestamp
False    525000
Name: count, dtype: int64

id
id
False    525000
Name: count, dtype: int64

title
title
False    525000
Name: count, dtype: int64

description
description
False    525000
Name: count, dtype: int64

category
category
False    525000
Name: count, dtype: int64

price
price
False    525000
Name: count, dtype: int64

discountPercentage
discountPercentage
False    525000
Name: count, dtype: int64

rating_y
rating_y
False    525000
Name: count, dtype: int64

stock
stock
False    525000
Name: count, dtype: int64

tags
tags
False    525000
Name: count, dtype: int64

brand
brand
False    263445
True     261555
Name: count, dtype: int64

sku
sku
False    525000
Name: count, dtype: int64

weight
weight
False    525000
Name: count, dtype: int64

dimensions
dimensions
False    525000
Name: count, dtype: int64

warrantyInformation
warrantyInformation
False    525000
Name: count, dtype: int64

shippingInformation
shippingInformation
False    525000
Name: count, dtype: int64

availabilityStatus
availabilityStatus
False    525000
Name: count, dtype: int64

reviews
reviews
False    525000
Name: count, dtype: int64

returnPolicy
returnPolicy
False    525000
Name: count, dtype: int64

minimumOrderQuantity
minimumOrderQuantity
False    525000
Name: count, dtype: int64

meta
meta
False    525000
Name: count, dtype: int64

images
images
False    525000
Name: count, dtype: int64

thumbnail
thumbnail
False    525000
Name: count, dtype: int64

## Missing Data Analysis Summary

**Dataset Overview:**
- Total Records: 26,250
- Total Columns: 27

**Missing Data Identified:**
- **brand**: 12,979 missing values (49.5%) - Significant missing data
- **All other columns**: No missing values ✓

**Analysis Details:**
- **Critical Identifiers** (user_id, product_id, id): No missing values ✓
- **Interaction Data** (interaction_type, rating_x, timestamp): No missing values ✓
- **Product Data** (title, description, category, price): No missing values ✓
- **Optional Attributes** (brand): 49.5% missing

**Key Finding:**
This is a high-quality dataset with minimal missing values. Only the 'brand' field requires handling due to ~50% missing data, which suggests brand information was not available for half the products in the source data.

**Handling Strategy:**
1. Fill missing 'brand' values with 'Unknown' category
2. Create a 'has_brand_info' flag to track original missing values for analysis
3. Keep all 26,250 records (no data loss)

### Handling Missing Brand Data

In [10]:
#firstly creating flag for missing brand info
df1['brand_info'] = df1['brand'].notna().astype(int)

#filling missing brand values with 'Unknown'
df1['brand'].fillna('Unknown', inplace=True)

#verifing the changes
print("Missing Data Handling Results:")
print("=" * 30)
print(f"Missing brand values after handling: {df1['brand'].isnull().sum()}")
print(f"\nBrand value counts:\n{df1['brand'].value_counts()}")
print(f"Missing values in 'brand_info' column: {df1['brand_info'].sum():,}")
print("Records with actual brand info (brand_info=0):", (df1['brand_info'] == 0).sum())

Missing Data Handling Results:
==============================
Missing brand values after handling: 0

Brand value counts:
brand
Unknown             261555
Annibale Colombo     34125
Knoll                18655
Velvet Touch         18235
Furniture Co.        18200
Calvin Klein         18095
Nail Couture         18025
Dolce & Gabbana      17850
Dior                 17710
Gucci                17430
Chic Cosmetics       17395
Chanel               17255
Glamour Beauty       17220
Essence              16765
Bath Trends          16485
Name: count, dtype: int64
Missing values in 'brand_info' column: 263,445
Records with actual brand info (brand_info=0): 261555

C:\Users\phema\AppData\Local\Temp\ipykernel_26640\2477042182.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['brand'].fillna('Unknown', inplace=True)

In [11]:
# Display cleaned data
print(f"Dataset shape: {df1.shape}")
print("\nFirst few rows:")
df1.head()

Dataset shape: (525000, 28)

First few rows:

,user_id,product_id,interaction_type,rating_x,timestamp,id,title,description,category,price,discountPercentage,rating_y,stock,tags,brand,sku,weight,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail,brand_info
0,2949,19,purchase,5,2026-04-01 21:17:02.978853,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,['meat'],Unknown,GRO-BRD-CHI-019,1,"{'width': 11.03, 'height': 22.11, 'depth': 16.01}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...,0
1,6162,24,view,3,2026-04-04 21:17:02.978866,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,['seafood'],Unknown,GRO-BRD-FIS-024,6,"{'width': 14.95, 'height': 26.31, 'depth': 11.27}",1 month warranty,Ships in 3-5 business days,In Stock,"[{'rating': 2, 'comment': 'Would not buy again...",60 days return policy,50,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...,0
2,6396,26,view,5,2026-03-23 21:17:02.978869,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,['vegetables'],Unknown,GRO-BRD-GRE-026,7,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...,0
3,9025,30,view,3,2026-04-11 21:17:02.978871,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,['fruits'],Unknown,GRO-BRD-KIW-030,5,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...,0
4,1372,16,view,5,2026-03-21 21:17:02.978873,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,['fruits'],Unknown,GRO-BRD-APP-016,9,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",['https://cdn.dummyjson.com/product-images/gro...,https://cdn.dummyjson.com/product-images/groce...,0

## Rating Column Consolidation

**Issue Identified:**
The dataset has two rating columns:
- **rating_x**: User's rating of the interaction/product
- **rating_y**: Product's average rating from metadata

These represent different perspectives and should be kept separate for comprehensive analysis.

**Action Taken:**
- Rename 'rating_x' → 'user_rating' (user's individual rating)
- Rename 'rating_y' → 'product_rating' (product's overall average)
- Both columns retained for full analysis

In [12]:
df1.rename(columns={
    'rating_x': 'user_rating',
    'rating_y': 'product_rating'
}, inplace=True)

print("Renamed columns:")
print(df1[['user_rating', 'product_rating']].head(10))

Renamed columns:
   user_rating  product_rating
0            5            3.19
1            3            3.78
2            5            3.66
3            3            4.93
4            5            4.19
5            1            4.55
6            2            3.59
7            4            4.55
8            3            2.53
9            1            4.80

In [13]:
#Correlation between user_rating and product_rating
correlation = df1['user_rating'].corr(df1['product_rating'])
print(f"Correlation between user_rating and product_rating: {correlation:.4f}")

Correlation between user_rating and product_rating: 0.0025

## Temporal Feature Extraction from timestamp

**Source Column:** timestamp

**Feature to Create**
- **hour**: Hour of Interaction (0-23)
- **day_of_week**: Day of week (0 - 6)
- **day_of_month**: Day of Month (1 - 31)
- **month**: Month of Year (1-12)
- **year**: Year
- **is_weekend**: Binary flag (1 for Sat/Sun) 0 otherwise
- **day_period**: Time period category (morning, afternoon, evening, night)

**Purpose:** Identify temporal patterns in user interactions

In [14]:
#converting timestamp to datetime
df1['timestamp'] = pd.to_datetime(df1['timestamp'], unit='s', errors='coerce')

#extracting temporal features
df1['hour'] = df1['timestamp'].dt.hour
df1['day_of_week'] = df1['timestamp'].dt.dayofweek
df1['day_of_month'] = df1['timestamp'].dt.day
df1['month'] = df1['timestamp'].dt.month
df1['year'] = df1['timestamp'].dt.year
df1['is_weekend'] = df1['day_of_week'].isin([5, 6]).astype(int)

#creating day period feature
def assign_day_period(hour):
    if 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

df1['day_period'] = df1['hour'].apply(assign_day_period)

print("Extracted temporal features and created 'day_period' feature.")
print(df1[['timestamp', 'hour', 'day_of_week', 'day_of_month', 'month', 'year', 'is_weekend', 'day_period']].head(10))
print(f"Unique values in 'day_period': {df1['day_period'].value_counts()}")

Extracted temporal features and created 'day_period' feature.
  timestamp  hour  day_of_week  day_of_month  month  year  is_weekend  \
0       NaT   NaN          NaN           NaN    NaN   NaN           0
1       NaT   NaN          NaN           NaN    NaN   NaN           0
2       NaT   NaN          NaN           NaN    NaN   NaN           0
3       NaT   NaN          NaN           NaN    NaN   NaN           0
4       NaT   NaN          NaN           NaN    NaN   NaN           0
5       NaT   NaN          NaN           NaN    NaN   NaN           0
6       NaT   NaN          NaN           NaN    NaN   NaN           0
7       NaT   NaN          NaN           NaN    NaN   NaN           0
8       NaT   NaN          NaN           NaN    NaN   NaN           0
9       NaT   NaN          NaN           NaN    NaN   NaN           0

  day_period
0      Night
1      Night
2      Night
3      Night
4      Night
5      Night
6      Night
7      Night
8      Night
9      Night
Unique values in 'day_period': day_period
Night    525000
Name: count, dtype: int64

## Text Column Cleaning and Standardization

**Text Columns to Clean:**
- title, description, category, tags, sku, brand, dimensions, warrantyInformation, shippingInformation, availabilityStatus, reviews, returnPolicy, meta

**Cleaning Operations:**
1. Removing leading/trailing whitespace
2. Converting to lowercase for consistency
3. Removing extra spaces between words
4. Handling special characters

**Purpose:** Standardize text for better analysis and feature engineering

In [15]:
# Clean text columns - remove extra spaces, convert to lowercase, and remove special characters
text_columns = ['title', 'description', 'category', 'tags', 'sku', 'brand',
             'dimensions', 'warrantyInformation', 'shippingInformation',
             'availabilityStatus', 'reviews', 'returnPolicy', 'meta']

for col in text_columns:
    if col in df1.columns:
        df1[col] = df1[col].astype(str).str.strip().str.lower()
#        df1[col] = df1[col].apply(lambda x: re.sub(r'[^\w\s]', '', x))
        df1[col] = df1[col].str.replace(r'\s+', ' ', regex=True)

#extract useful info from dimensions column
df1['description_word_count'] = df1['description'].apply(lambda x: len(str(x).split()))
df1['title_word_count'] = df1['title'].apply(lambda x: len(str(x).split()))
df1['tags_count'] = df1['tags'].apply(lambda x: len(str(x).split(',')) if isinstance(x, str) else 0)

In [16]:
print("Extracted word count features from 'description', 'title', and 'tags' columns.")
print(f"\nDescription word count stats:\n{df1['description_word_count'].describe()}")
print(f"\nTitle word count stats:\n{df1['title_word_count'].describe()}")
print(f"\nTags count stats:\n{df1['tags_count'].describe()}")

Extracted word count features from 'description', 'title', and 'tags' columns.

Description word count stats:
count    525000.000000
mean         18.568333
std           6.650059
min           9.000000
25%          13.000000
50%          21.000000
75%          24.000000
max          31.000000
Name: description_word_count, dtype: float64

Title word count stats:
count    525000.000000
mean          2.706533
std           1.238338
min           1.000000
25%           2.000000
50%           2.000000
75%           4.000000
max           5.000000
Name: title_word_count, dtype: float64

Tags count stats:
count    525000.0000
mean          1.5684
std           0.4953
min           1.0000
25%           1.0000
50%           2.0000
75%           2.0000
max           2.0000
Name: tags_count, dtype: float64

## Outlier Detection (IQR Method)

**Columns to Check for Outliers:**
- **price**: Product price
- **discountPercentage**: Discount percentage
- **stock**: Inventory levels
- **weight**: Product weight
- **user_rating**: User ratings (should be 0-5)
- **product_rating**: Product ratings (should be 0-5)

**Method:** Interquartile Range (IQR)
- Calculate Q1 (25th percentile) and Q3 (75th percentile)
- IQR = Q3 - Q1
- Lower bound = Q1 - 1.5 × IQR
- Upper bound = Q3 + 1.5 × IQR

**Action:** Flag outliers but keep them for analysis (don't delete)

In [17]:
## Outliers Detection (IQR Method)
def detect_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = (df[column] < lower_bound) | (df[column] > upper_bound)
    return outliers, lower_bound, upper_bound

In [18]:
numerical_columns = ['price', 'discountPercentage', 'stock', 'weight', 'user_rating', 'product_rating']

#Detection of outliers for each numerical column
outlier_summary = {}
for col in numerical_columns:
    outliers, lower_bound, upper_bound = detect_outliers_iqr(df1, col)
    cnt = outliers.sum()
    outlier_summary[col] = {
        'count': cnt,
        'outlier_count': outliers.sum(),
        'percentage': (cnt / len(df1)) * 100,
        'lower_bound': lower_bound,
        'upper_bound': upper_bound
    }

    print(f"\n{col} Outliers:"
          f"\nLower Bound: {lower_bound:.2f}"
          f"\nUpper Bound: {upper_bound:.2f}"
          f"\nOutliers Count: {cnt:,} ({(cnt / len(df1)) * 100:.2f}%)")
    

# Creating outlier flag column
df1['has_outlier'] = False
for col in numerical_columns:
    outliers, lower_bound, upper_bound = detect_outliers_iqr(df1, col)
    df1.loc[outliers, 'has_outlier'] = True

print(f"\nTotal records with outliers in any numerical column: {df1['has_outlier'].sum():,} ({(df1['has_outlier'].mean() * 100):.2f}%)")

price Outliers:
Lower Bound: -107.51
Upper Bound: 192.49
Outliers Count: 87,465 (16.66%)

discountPercentage Outliers:
Lower Bound: -0.16
Upper Bound: 23.12
Outliers Count: 0 (0.00%)

stock Outliers:
Lower Bound: -64.50
Upper Bound: 179.50
Outliers Count: 0 (0.00%)

weight Outliers:
Lower Bound: -8.50
Upper Bound: 19.50
Outliers Count: 0 (0.00%)

user_rating Outliers:
Lower Bound: -1.00
Upper Bound: 7.00
Outliers Count: 0 (0.00%)

product_rating Outliers:
Lower Bound: 1.57
Upper Bound: 6.05
Outliers Count: 0 (0.00%)

Total records with outliers in any numerical column: 87,465 (16.66%)

## Data Type Optimization for Memory Efficiency

**Purpose:** Reduce memory footprint and improve performance

**Optimizations:**
- Convert object columns to **categorical** (user_id, product_id, category, brand, interaction_type, availabilityStatus)
- Convert integer columns to **int32** where appropriate (stock, weight, minimumOrderQuantity)
- Keep float columns as-is

**Expected Result:** ~40-50% memory reduction

In [19]:
#Conversion of categorical values to reduce memory usage significantly for repeated values
categorical_cols = ['user_id', 'product_id', 'category', 'brand', 
                    'interaction_type', 'availabilitystatus', 'sku']

for col in categorical_cols:
    if col in df1.columns:
        df1[col] = df1[col].astype('category')


#conversion of integer cols to int32 
int_cols = ['stock', 'weight', 'minimumOrderQuality']
for col in int_cols:
    if col in df1.columns:
        df1[col] = pd.to_numeric(df1[col], errors='coerce').fillna(0).astype(np.int32)

In [20]:
#memory utilization
memory_usage = df1.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"\nMemory usage after optimization: {memory_usage:.2f} MB")

print(f"\nData types after optimization:\n{df1.dtypes}")

Memory usage after optimization: 1025.10 MB

Data types after optimization:
user_id                         category
product_id                      category
interaction_type                category
user_rating                        int64
timestamp                 datetime64[ns]
id                                 int64
title                             object
description                       object
category                        category
price                            float64
discountPercentage               float64
product_rating                   float64
stock                              int32
tags                              object
brand                           category
sku                             category
weight                             int32
dimensions                        object
warrantyInformation               object
shippingInformation               object
availabilityStatus                object
reviews                           object
returnPolicy                      object
minimumOrderQuantity               int64
meta                              object
images                            object
thumbnail                         object
brand_info                         int32
hour                             float64
day_of_week                      float64
day_of_month                     float64
month                            float64
year                             float64
is_weekend                         int32
day_period                        object
description_word_count             int64
title_word_count                   int64
tags_count                         int64
has_outlier                         bool
dtype: object

## Duplicate Records Detection

**Check Types:**
1. **Complete Duplicates**: Identical across all columns
2. **Functional Duplicates**: Same user-product-timestamp combination
3. **Repeat Interactions**: Same user-product pair (different timestamps)

**Action:** Flag duplicates for analysis (retain all records)

In [21]:
#check for complete duplicates
complete_duplicates = df1.duplicated().sum()
print(f"Complete duplicate records: {complete_duplicates:}")

#check for functional duplicates based on user_id, product_id, and interaction_type
functional_duplicates = df1.duplicated(subset=['user_id', 'product_id', 'interaction_type']).sum()
print(f"Functional duplicate records (based on user_id, product_id, interaction_type): {functional_duplicates}")

#check for repeated interactions between same user and product
repeated_interactions = df1.duplicated(subset=['user_id', 'product_id']).sum()
print(f"Repeated interactions (based on user_id, product_id): {repeated_interactions}")

#flagging duplicates for potential removal
df1['is_duplicate'] = df1.duplicated(subset=['user_id', 'product_id'], keep=False).astype(int)

print(f"\nTotal records flagged as duplicates (based on user_id and product_id): {df1['is_duplicate'].sum():,} ({(df1['is_duplicate'].mean() * 100):.2f}%)")

Complete duplicate records: 510022
Functional duplicate records (based on user_id, product_id, interaction_type): 510120
Repeated interactions (based on user_id, product_id): 510371

Total records flagged as duplicates (based on user_id and product_id): 525,000 (100.00%)

## Data Normalization

**Purpose:** Scale numerical features to a standard range [0, 1]

**Columns to Normalize:**
- price
- discountPercentage
- stock
- weight
- user_rating
- product_rating

**Method:** MinMax Scaling
- Formula: X_normalized = (X - X_min) / (X_max - X_min)
- Result: All values fall between 0 and 1
- Advantage: Preserves the shape of original distribution
- Use Case: Machine learning models sensitive to feature scaling

**Why:** Different features have different ranges (price 0-5000, ratings 0-5). Normalization ensures equal importance in downstream analysis.

In [22]:
from sklearn.preprocessing import MinMaxScaler

# Columns to normalize
numerical_cols_to_normalize = ['price', 'discountPercentage', 'stock', 'weight', 'user_rating', 'product_rating']

# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Apply normalization
df1[['price_normalized', 'discount_normalized', 'stock_normalized', 
     'weight_normalized', 'user_rating_normalized', 'product_rating_normalized']] = \
    scaler.fit_transform(df1[numerical_cols_to_normalize])

print("Data Normalization Completed:")
print("=" * 70)
print("\nNormalized Columns Statistics:")
normalized_cols = ['price_normalized', 'discount_normalized', 'stock_normalized', 
                   'weight_normalized', 'user_rating_normalized', 'product_rating_normalized']
print(df1[normalized_cols].describe())

print("\nSample comparison (Original vs Normalized):")
comparison_df = pd.DataFrame({
    'price_original': df1['price'].head(),
    'price_normalized': df1['price_normalized'].head(),
    'rating_original': df1['user_rating'].head(),
    'rating_normalized': df1['user_rating_normalized'].head()
})
print(comparison_df)

Data Normalization Completed:
======================================================================

Normalized Columns Statistics:
       price_normalized  discount_normalized  stock_normalized  \
count     525000.000000        525000.000000     525000.000000
mean           0.085781             0.509307          0.540826
std            0.221494             0.284849          0.346432
min            0.000000             0.000000          0.000000
25%            0.001601             0.444268          0.250000
50%            0.004802             0.534073          0.593750
75%            0.031613             0.751717          0.885417
max            1.000000             1.000000          1.000000

       weight_normalized  user_rating_normalized  product_rating_normalized
count      525000.000000           525000.000000              525000.000000
mean            0.534600                0.503550                   0.553106
std             0.353810                0.355633                   0.292640
min             0.000000                0.000000                   0.000000
25%             0.111111                0.250000                   0.300000
50%             0.555556                0.500000                   0.595833
75%             0.888889                0.750000                   0.766667
max             1.000000                1.000000                   1.000000

Sample comparison (Original vs Normalized):
   price_original  price_normalized  rating_original  rating_normalized
0            9.99          0.003601                5                1.0
1           14.99          0.005602                3                0.5
2            0.99          0.000000                5                1.0
3            2.49          0.000600                3                0.5
4            1.99          0.000400                5                1.0

## Data Standardization (Z-Score Scaling)

**Purpose:** Transform features to have mean = 0 and standard deviation = 1

**Columns to Standardize:**
- price
- discountPercentage
- stock
- weight

**Method:** StandardScaler (Z-Score)
- Formula: X_standardized = (X - mean) / std_dev
- Result: Bell-curve centered at 0
- Advantage: Better for algorithms assuming normally distributed data
- Use Case: Linear/Logistic Regression, SVM, Neural Networks

**When to Use:** When data follows normal distribution or when comparing across different scales

In [23]:
from sklearn.preprocessing import StandardScaler

# Columns to standardize
numerical_cols_to_standardize = ['price', 'discountPercentage', 'stock', 'weight']

# Initialize StandardScaler
std_scaler = StandardScaler()

# Apply standardization
df1[['price_standardized', 'discount_standardized', 'stock_standardized', 
     'weight_standardized']] = \
    std_scaler.fit_transform(df1[numerical_cols_to_standardize])

print("Data Standardization (Z-Score) Completed:")
print("=" * 70)
print("\nStandardized Columns Statistics (should have mean≈0, std≈1):")
standardized_cols = ['price_standardized', 'discount_standardized', 
                     'stock_standardized', 'weight_standardized']
stats = df1[standardized_cols].describe()
print(stats)

print("\nVerification (Mean should be ≈ 0, Std should be ≈ 1):")
for col in standardized_cols:
    print(f"{col}: Mean = {df1[col].mean():.6f}, Std = {df1[col].std():.6f}")

Data Standardization (Z-Score) Completed:
======================================================================

Standardized Columns Statistics (should have mean≈0, std≈1):
       price_standardized  discount_standardized  stock_standardized  \
count        5.250000e+05           5.250000e+05        5.250000e+05
mean         3.014681e-16          -2.389724e-16       -2.791080e-17
std          1.000001e+00           1.000001e+00        1.000001e+00
min         -3.872847e-01          -1.787988e+00       -1.561136e+00
25%         -3.800581e-01          -2.283254e-01       -8.394923e-01
50%         -3.656050e-01           8.694536e-02        1.527680e-01
75%         -2.445600e-01           8.510132e-01        9.946859e-01
max          4.127512e+00           1.722644e+00        1.325439e+00

       weight_standardized
count         5.250000e+05
mean          5.892768e-17
std           1.000001e+00
min          -1.510981e+00
25%          -1.196939e+00
50%           5.922829e-02
75%           1.001354e+00
max           1.315396e+00

Verification (Mean should be ≈ 0, Std should be ≈ 1):
price_standardized: Mean = 0.000000, Std = 1.000001
discount_standardized: Mean = -0.000000, Std = 1.000001
stock_standardized: Mean = -0.000000, Std = 1.000001
weight_standardized: Mean = 0.000000, Std = 1.000001

## Data Binning (Discretization)

**Purpose:** Convert continuous numerical values into discrete categorical bins

**Columns to Bin:**
1. **price** → Price ranges (Budget, Mid-range, Premium, Luxury)
2. **discountPercentage** → Discount levels (No Discount, Low, Medium, High)
3. **product_rating** → Rating categories (Poor, Below Average, Average, Good, Excellent)
4. **stock** → Inventory levels (Out of Stock, Low, Medium, High)

**Method:** Equal-width binning based on domain knowledge

**Benefits:**
- Simplifies data analysis
- Reduces impact of outliers
- Creates interpretable categories
- Useful for visualization and business rules

In [25]:
# 1. Price Binning
price_max = df1['price'].max()
price_bins = [0, 50, 200, 500, price_max + 1]
price_labels = ['Budget', 'Mid-range', 'Premium', 'Luxury']
df1['price_category'] = pd.cut(df1['price'], bins=price_bins, labels=price_labels, include_lowest=True)

# 2. Discount Percentage Binning
discount_bins = [-0.1, 0, 20, 50, 101]
discount_labels = ['No Discount', 'Low', 'Medium', 'High']
df1['discount_category'] = pd.cut(df1['discountPercentage'], bins=discount_bins, 
                                   labels=discount_labels, include_lowest=True)

# 3. Product Rating Binning
rating_bins = [0, 1, 2, 3, 4, 5.1]
rating_labels = ['Poor', 'Below Average', 'Average', 'Good', 'Excellent']
df1['product_rating_category'] = pd.cut(df1['product_rating'], bins=rating_bins, 
                                         labels=rating_labels, include_lowest=True)

# 4. Stock Level Binning (FIXED - Dynamic bins)
stock_min = df1['stock'].min()
stock_max = df1['stock'].max()
stock_bins = [stock_min - 1, 10, 30, 60, stock_max + 1]  # Fixed: strictly increasing values
stock_labels = ['Out of Stock', 'Low', 'Medium', 'High']
df1['stock_category'] = pd.cut(df1['stock'], bins=stock_bins, labels=stock_labels, include_lowest=True)

print("Data Binning Completed:")
print("=" * 70)

print("\n1. Price Categories:")
print(f"   Bins: {price_bins}")
print(df1['price_category'].value_counts().sort_index())

print("\n2. Discount Categories:")
print(f"   Bins: {discount_bins}")
print(df1['discount_category'].value_counts().sort_index())

print("\n3. Product Rating Categories:")
print(f"   Bins: {rating_bins}")
print(df1['product_rating_category'].value_counts().sort_index())

print("\n4. Stock Categories:")
print(f"   Bins: {stock_bins}")
print(df1['stock_category'].value_counts().sort_index())

print("\nSample binned data:")
print(df1[['price', 'price_category', 'discountPercentage', 'discount_category', 
           'product_rating', 'product_rating_category', 'stock', 'stock_category']].head(10))

Data Binning Completed:
======================================================================

1. Price Categories:
   Bins: [0, 50, 200, 500, 2500.99]
price_category
Budget       367290
Mid-range     70245
Premium       36855
Luxury        50610
Name: count, dtype: int64

2. Discount Categories:
   Bins: [-0.1, 0, 20, 50, 101]
discount_category
No Discount         0
Low            525000
Medium              0
High                0
Name: count, dtype: int64

3. Product Rating Categories:
   Bins: [0, 1, 2, 3, 4, 5.1]
product_rating_category
Poor                  0
Below Average         0
Average           87570
Good             209545
Excellent        227885
Name: count, dtype: int64

4. Stock Categories:
   Bins: [2, 10, 30, 60, 100]
stock_category
Out of Stock    104370
Low              54215
Medium          120295
High            246120
Name: count, dtype: int64

Sample binned data:
    price price_category  discountPercentage discount_category  \
0    9.99         Budget               13.70               Low
1   14.99         Budget                4.23               Low
2    0.99         Budget                1.00               Low
3    2.49         Budget               15.22               Low
4    1.99         Budget               12.62               Low
5   10.99         Budget               10.27               Low
6  799.99         Luxury                8.80               Low
7   10.99         Budget               10.27               Low
8    2.99         Budget               11.05               Low
9    4.99         Budget                9.33               Low

   product_rating product_rating_category  stock stock_category
0            3.19                    Good     97           High
1            3.78                    Good     74           High
2            3.66                    Good      3   Out of Stock
3            4.93               Excellent     99           High
4            4.19               Excellent      8   Out of Stock
5            4.55               Excellent     71           High
6            3.59                    Good      7   Out of Stock
7            4.55               Excellent     71           High
8            2.53                 Average      9   Out of Stock
9            4.80               Excellent     10   Out of Stock

## Data Wrangling

**Purpose:** Clean, transform, and restructure data for analysis

**Operations:**
1. Handle inconsistent category values (standardize text)
2. Remove special characters from text fields
3. Handle unexpected data types
4. Validate and fix data format issues
5. Remove or encode categorical outliers
6. Handle zero/negative values in specific columns

**Why Important:** Ensures consistency and quality for downstream analysis and modeling

In [28]:
# 1. Standardize categorical columns (lowercase, strip whitespace)
categorical_columns_to_clean = ['category', 'interaction_type', 'availabilityStatus']

for col in categorical_columns_to_clean:
    if col in df1.columns:
        df1[col] = df1[col].str.lower().str.strip()
        print(f"{col} unique values: {df1[col].nunique()}")
        print(df1[col].value_counts().head())
        print()

# 2. Handle interaction_type - ensure only valid types
valid_interactions = ['purchase', 'view', 'cart', 'add', 'remove', 'wishlist']
print(f"Unique interaction types in data:")
print(df1['interaction_type'].unique())

# 2. Fix availability status - standardize values
print(f"\nAvailability Status - Before wrangling:")
print(df1['availabilityStatus'].value_counts())

# Map similar values
availability_mapping = {
    'in stock': 'in stock',
    'out of stock': 'out of stock',
    'limited stock': 'limited stock',
    'back order': 'back order',
    'discontinued': 'discontinued'
}

df1['availabilityStatus'] = df1['availabilityStatus'].map(
    lambda x: availability_mapping.get(x, x) if x in availability_mapping.values() else 'unknown'
)

print(f"\nAvailability Status - After wrangling:")
print(df1['availabilityStatus'].value_counts())

# 3. Ensure numerical columns have no unexpected strings
# Convert any non-numeric values to NaN, then fill with median/default
df1['stock'] = pd.to_numeric(df1['stock'], errors='coerce').fillna(df1['stock'].median())
df1['weight'] = pd.to_numeric(df1['weight'], errors='coerce').fillna(df1['weight'].median())

# 4. Fix negative values where they shouldn't exist
df1['stock'] = df1['stock'].clip(lower=0)  # Stock can't be negative
df1['weight'] = df1['weight'].clip(lower=0.1)  # Weight should be positive

# 5. Ensure price is always positive
df1['price'] = df1['price'].clip(lower=0.01)  # Minimum price

# 6. Discount percentage must be 0-100
df1['discountPercentage'] = df1['discountPercentage'].clip(0, 100)

# 7. Ratings must be 0-5
df1['user_rating'] = df1['user_rating'].clip(0, 5)
df1['product_rating'] = df1['product_rating'].clip(0, 5)

print("\nData Wrangling Completed:")
print("=" * 70)
print(" Fixed availability status values")
print(" Converted non-numeric values")
print(" Standardized categorical columns")
print(" Removed negative values from non-negative columns")
print(" Constrained values to valid ranges")

print("\nData ranges after wrangling:")
print(f"Price range: {df1['price'].min():.2f} - {df1['price'].max():.2f}")
print(f"Discount range: {df1['discountPercentage'].min():.2f}% - {df1['discountPercentage'].max():.2f}%")
print(f"Stock range: {df1['stock'].min():.0f} - {df1['stock'].max():.0f}")
print(f"User rating range: {df1['user_rating'].min():.1f} - {df1['user_rating'].max():.1f}")
print(f"Product rating range: {df1['product_rating'].min():.1f} - {df1['product_rating'].max():.1f}")

category unique values: 4
category
groceries     261555
fragrances     88340
beauty         87640
furniture      87465
Name: count, dtype: int64

interaction_type unique values: 3
interaction_type
view        175910
click       175595
purchase    173495
Name: count, dtype: int64

availabilityStatus unique values: 2
availabilityStatus
in stock    472080
unknown      52920
Name: count, dtype: int64

Unique interaction types in data:
['purchase' 'view' 'click']

Availability Status - Before wrangling:
availabilityStatus
in stock    472080
unknown      52920
Name: count, dtype: int64

Availability Status - After wrangling:
availabilityStatus
in stock    472080
unknown      52920
Name: count, dtype: int64

Data Wrangling Completed:
======================================================================
 Fixed availability status values
 Converted non-numeric values
 Standardized categorical columns
 Removed negative values from non-negative columns
 Constrained values to valid ranges

Data ranges after wrangling:
Price range: 0.99 - 2499.99
Discount range: 0.16% - 19.09%
Stock range: 3 - 99
User rating range: 1.0 - 5.0
Product rating range: 2.5 - 4.9

In [29]:
print("\nPre-Validation Dataset Overview:")
print("=" * 70)
print(f"\nDataset Shape: {df1.shape}")
print(f"Total Records: {len(df1):,}")
print(f"Total Features: {len(df1.columns)}")
print(f"Memory Usage: {df1.memory_usage(deep=True).sum() / (1024**2):.2f} MB")

print(f"\nNew Features Created:")
new_features = ['brand_info', 'hour', 'day_of_week', 'day_period', 'is_weekend', 
                'description_word_count', 'title_word_count', 'tags_count', 
                'has_outlier', 'is_duplicate',
                'price_normalized', 'discount_normalized', 'stock_normalized', 
                'weight_normalized', 'user_rating_normalized', 'product_rating_normalized',
                'price_standardized', 'discount_standardized', 'stock_standardized', 
                'weight_standardized',
                'price_category', 'discount_category', 'product_rating_category', 'stock_category']

print(f"  - Total new features: {len(new_features)}")
for feature in new_features:
    if feature in df1.columns:
        print(f"    ✓ {feature}")

print(f"\nData Quality Flags:")
print(f"  - Records with missing brand info: {(df1['brand_info'] == 0).sum():,}")
print(f"  - Records with outliers: {df1['has_outlier'].sum():,}")
print(f"  - Duplicate records: {df1['is_duplicate'].sum():,}")
print(f"  - Weekend interactions: {df1['is_weekend'].sum():,}")

print("\n✓ Ready for Data Quality Validation Report!")

Pre-Validation Dataset Overview:
======================================================================

Dataset Shape: (525000, 54)
Total Records: 525,000
Total Features: 54
Memory Usage: 1133.68 MB

New Features Created:
  - Total new features: 24
    ✓ brand_info
    ✓ hour
    ✓ day_of_week
    ✓ day_period
    ✓ is_weekend
    ✓ description_word_count
    ✓ title_word_count
    ✓ tags_count
    ✓ has_outlier
    ✓ is_duplicate
    ✓ price_normalized
    ✓ discount_normalized
    ✓ stock_normalized
    ✓ weight_normalized
    ✓ user_rating_normalized
    ✓ product_rating_normalized
    ✓ price_standardized
    ✓ discount_standardized
    ✓ stock_standardized
    ✓ weight_standardized
    ✓ price_category
    ✓ discount_category
    ✓ product_rating_category
    ✓ stock_category

Data Quality Flags:
  - Records with missing brand info: 261,555
  - Records with outliers: 87,465
  - Duplicate records: 525,000
  - Weekend interactions: 0

✓ Ready for Data Quality Validation Report!

## Data Quality Validation

**Validation Checks:**
1. **Logical Ranges:**
   - Price: > 0
   - Discount: 0-100%
   - Ratings: 0-5 (for both user and product ratings)
   - Stock: >= 0
   - Weight: > 0

2. **Data Integrity:**
   - No NULL values in any column
   - Consistent data types
   - Valid categories
   - Valid timestamps

3. **Business Logic:**
   - User IDs are valid
   - Product IDs are valid
   - Timestamps are reasonable

In [30]:
print("Data Quality Validation Report")
print("=" * 70)

# 1. Null values check
null_count = df1.isnull().sum().sum()
print(f"\n1. Total NULL values in dataset: {null_count}")
if null_count == 0:
    print("   ✓ No NULL values found")

# 2. Price validation
invalid_price = (df1['price'] <= 0).sum()
print(f"\n2. Invalid prices (≤ 0): {invalid_price}")
if invalid_price == 0:
    print("   ✓ All prices are valid")

# 3. Discount validation
invalid_discount = ((df1['discountPercentage'] < 0) | (df1['discountPercentage'] > 100)).sum()
print(f"\n3. Invalid discount percentages (not 0-100): {invalid_discount}")
if invalid_discount == 0:
    print("   ✓ All discount percentages are valid")

# 4. Rating validation
invalid_user_rating = ((df1['user_rating'] < 0) | (df1['user_rating'] > 5)).sum()
invalid_product_rating = ((df1['product_rating'] < 0) | (df1['product_rating'] > 5)).sum()
print(f"\n4. Invalid user ratings: {invalid_user_rating}")
print(f"5. Invalid product ratings: {invalid_product_rating}")
if invalid_user_rating == 0 and invalid_product_rating == 0:
    print("   ✓ All ratings are in valid range (0-5)")

# 5. Stock validation
invalid_stock = (df1['stock'] < 0).sum()
print(f"\n6. Invalid stock (< 0): {invalid_stock}")
if invalid_stock == 0:
    print("   ✓ All stock values are non-negative")

# 6. Weight validation
invalid_weight = (df1['weight'] <= 0).sum()
print(f"\n7. Invalid weights (≤ 0): {invalid_weight}")

# 7. Timestamp validation
invalid_timestamps = df1['timestamp'].isnull().sum()
print(f"\n8. Invalid timestamps: {invalid_timestamps}")

print("\n" + "=" * 70)
print("✓ Data Quality Validation Complete")

Data Quality Validation Report
======================================================================

1. Total NULL values in dataset: 3150000

2. Invalid prices (≤ 0): 0
   ✓ All prices are valid

3. Invalid discount percentages (not 0-100): 0
   ✓ All discount percentages are valid

4. Invalid user ratings: 0
5. Invalid product ratings: 0
   ✓ All ratings are in valid range (0-5)

6. Invalid stock (< 0): 0
   ✓ All stock values are non-negative

7. Invalid weights (≤ 0): 0

8. Invalid timestamps: 525000

======================================================================
✓ Data Quality Validation Complete

In [31]:
df1.to_csv(r"e:/dm4ml project/data/processed/final_dataset_cleaned.csv", index=False)
print("\nCleaned dataset saved to 'final_dataset_cleaned.csv'")

Cleaned dataset saved to 'final_dataset_cleaned.csv'